### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by charleslouis** [justafish/drupal_amazons3#12]
Hi there,

I've been struggling for a day around the following :
I leave in Paris, and found logical (is it ?) to create a bucket in Frankfurt.

The thing is, Frankfurt doesn't support V2.

see : 
http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4
"
AWS4-HMAC-SHA256, also known as "V4," is one of two authentication schemes in S3.

US-Standard, and many -- but not all -- other regions, also support the other, older scheme, V2.

According to http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html ... new S3 regions deployed after January, 2014 will only support V4.

Since Frankfurt was introduced late in 2014, it apparently does not support V2, which is what this error suggests you are using.

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html explains how to enable V4 in the various SDKs, assuming you are using an SDK that has that capability.

I would speculate that some older versions of the SDKs might not support this option, so if the above doesn't help, you may need a newer release of the SDK you are using.
"

But the only thing we are aware when an error is occuring, is that the response is not ok

```
 if (!$s3->if_bucket_exists($bucket) || !$response->isOK()) {
        form_set_error('amazons3_bucket', t('The S3 access credentials are invalid or the bucket does not exist'));
      }
```

So, if like me you're using Frankfurt, there is no way to know that the drupal authentication scheme is not supported by your bucket. And you end up blaming your user/policies/credentials.

Maybe we could enrich the error message like so, as a temporary solution before V4 is implemented ?

```
      if (!$s3->if_bucket_exists($bucket) || !$response->isOK()) {
        form_set_error('amazons3_bucket', t('The S3 access credentials are invalid or the bucket does not exist. Also, make sure that your bucket uses a V2 authentification scheme. The safest would be Oregon or Us Standard for now. If your bucket is in Frankfurt or elsewhere, it might not work.'));
      }
```

Best,
Charles-Louis

**Comment by deviantintegral** [comment]
@charleslouis can you try with the 7.x-2.x branch? The two known missing features on it are support for reduced redundancy storage, and it only covers 95% of what you could do with the hooks in the 7.x-1.x. branch.

**Comment by charleslouis** [comment]
Hi @deviantintegral,

Thank you for your answer.
At the moment I can't take time to test with 7.x-2.x but as soon as I can I'll let you know how things goes.
I switched to a US bucket and it works for now.

Best,
Charles-Louis
