### ISSUE TITLE
Image Style Derivatives not generated for Copyright images and images with meta information

### ISSUE THREAD

**Issue by crystalpaladin** [justafish/drupal_amazons3#28]
Normal Drupal Public Filesystem can generate image styles for all images including Copyrighted and images with meta information like (datemodified:date,software:adobe photoshopcs3, Copyright information)

But after Setting up S3, These are the Observations:
1) The original file gets stored in S3 Bucket. and available/accessible as a public asset
2) The Image Style derivative URL points to the server but no image is available
3) The directory /tmp/amazons3/styles/ doesn't have the generated image
4) cache_amazons3_metadata table (seems like doctrine cache) has some blob objects related to the image styles. every entry seems to be 558KB size but original file size is 317.7KB
5) file_managed table has the actual file entry
6) error reported in logs is the following:
Exception: Amazon S3 was unable to create an image style derivative. Check the temporary directory configuration and permissions. in amazons3_image_deliver() (line 139 of /var/www/html/sites/all/modules/contrib/amazons3/amazons3.module).
7) The actual image file size is 317KB and image dimensions are 2001x1429 (this info might be irrelevant but hey I thought you should know)

Though other images seems to be working fine and didn't report any permission issues.
Or Is it the permission got attached to the copyrighted file and causes this issue
Or Is amazonS3 / SDK prohibits modification of images with meta information or copyrighted.

**Comment by crystalpaladin** [comment]
No Issues observed with GD Library as the same copyrighted image can be scaled, cropped and JPEG Compression applied normally and the image styles can be accessed publicly
(observed with S3 disabled for the image field)

**Comment by crystalpaladin** [comment]
Images under consideration are:
![pti5_15_2015_000315b](https://cloud.githubusercontent.com/assets/12294024/7665052/2fc8ba06-fbc4-11e4-9185-c01e3dda4e87.jpg)
![pti5_15_2015_000309b_1](https://cloud.githubusercontent.com/assets/12294024/7665053/34343dc2-fbc4-11e4-988a-38b4a08db73f.jpg)
![9333](https://cloud.githubusercontent.com/assets/12294024/7665056/430efa1c-fbc4-11e4-96e4-293ba333b93e.jpg)

**Comment by deviantintegral** [comment]
@crystalpaladin are you using ImageMagick on your site? It runs as a shell command and not a PHP module, so it doesn't work as-is with stream wrappers. You'd need <a href="https://github.com/justafish/drupal_amazons3#image-styles">the patch linked in the README</a> for it to work right.

**Comment by crystalpaladin** [comment]
No I use GD Lampp stack package...

**Comment by crystalpaladin** [comment]
@deviantintegral
Sorry... I kinda confused the statements... Here is the fact:
I use GD Library and not imagemagick. I hope that runs via php fuctions...
1) Public file system works fine...ie all scaling, cropping and jpeg compression stuff
2) But when I switch the filesystem to S3, the actual file gets transferred to S3 without any issues... but when various image styles are requested for the image, the amazon wrapper gives the image derivative urls("amazons3/image-derivative/&lt;bucket-name&gt;/styles/&lt;style-name&gt;/&lt;image-file-name&gt;"). but the urls doesn't have any images associated with it...

**Comment by deviantintegral** [comment]
@crystalpaladin you were totally right about it being related to the EXIF metadata. Images taken with my Nexus 5 work fine, but with my Panasonic camera they fail. It looks to at least be related to the Maker Info tags, but it wouldn't surprise me if other conditions trigger it too. I can replicate this using the AWS SDK without Drupal, so it looks to be a combination of PHP and AWS SDK issues. I filed more details over at https://github.com/aws/aws-sdk-php/issues/587

Can you try the patch from https://github.com/justafish/drupal_amazons3/pull/30 ? It works around the issue by doing a local file transfer first, and using that instead of S3 directly. It should be the same performance since generating a derivative requires a file transfer anyways.

**Comment by crystalpaladin** [comment]
@deviantintegral, The patch worked... I'll check it with few other image formats with different meta information and confirm the same(although it won't make a difference since all meta are meta and the patch will work. but for the record I'll do it)...

about the side-effect you've mentioned in the #30 , I'll check it for image cropping module and preview features and confirm the same...

So I assume, after referring  aws/aws-sdk-php#587 once amazon v3 gets integrated in amazons3 module, this patch is not needed. but that won't happen anytime soon since this has been marked as enhancement and will be included sometime later...

**Comment by deviantintegral** [comment]
I certainly want to get this fixed against the 2.x SDK, but long-term it would be better if PHP and the AWS SDK would handle this all for us. It doesn't make sense for Drupal, Wordpress, and every other custom system to have to work around this individually.

I'm going to take a look into the upload button issue now.

**Comment by deviantintegral** [comment]
I figured out the upload issue; image module was also calling image_get_info(), but in a way that didn't hit any amazons3 module code.

I think I've got a way to solve this cleanly upstream, where all we'd have to do is enable seekable streams in the stream wrapper on our end: https://github.com/aws/aws-sdk-php/pull/589

If there's no major issues with that PR, I'll integrate it over here for testing.

**Comment by deviantintegral** [comment]
I've merged #30 in.
