### ISSUE TITLE
Region should not be autodetermine

### ISSUE THREAD

**Issue by donaldinou** [justafish/drupal_amazons3#44]
We need region support for this module.
I see in the master branch that there is some code about region for the factory (S3Client).
But, I think that it should not be auto determine (because actually it does not work), and should be configurable (like the other parameters)

example (factory function for the S2Client class):

```
    if (!isset($config[''])) {
      $region = static::variable_get('amazons3_region');
      if (!empty($region)) {
        $config['region'] = $region;
      }
    }
```

With that way, user can correctly manage s3bucket in drupal

**Comment by deviantintegral** [comment]
This should be fixed now in the latest dev release.
